version: "3.8"

services:
  api:
    build: .
    ports:
      - "8000:80"
    environment:
      - DATABASE_URL=postgres://user:password@db/orders
    depends_on:
      - db
    networks:
      - backend

  db:
    image: postgres:13-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: orders
    volumes:
      - db_data:/var/lib/postgresql/data/
    networks:
      - backend

volumes:
  db_data:

networks:
  backend:
